### ISSUE TITLE
Review of repository and MATLAB code (Work in Progress)

### ISSUE THREAD

**Issue by TimVanMourik** [RainCloudPlots/RainCloudPlots#7]
I played around with the initial version of the MATLAB toolbox as provided by @TomRhysMarshall. Here some comments (WIP) and associated PRs will follow soon.

## Review of repository 
* [ ] Copies of the example data is present to both Python and Matlab directories. I can see that your reasoning is that it keeps languages separate, but it prevents me from modifying the example data and immediately seeing the changes in both scripts. From a Don't Repeat Yourself (DRY) coding principle I recommend a single tutorial directory. See WIP PR #8.
* [x] All code folders are called `tutorial_XXX`, but it's not only tutorial code. I see this repository as a code repository with `/python`, '/matlab`, and `/r` code, all of which happen to include tutorials. I recommend restructuring. See WIP PR #8.
## Review of MATLAB
* [x] The tutorial file is MATLAB2018a+, which is very modern but therefore slightly less accessible. 
  * I'm cool with `.mlx` files, but they're MATLAB2016a+ only, and not necessarily widely used.  An old-school Matlab legacy script might be appreciated, also for people that use MATLAB more programmatically instead.
  * Double quote syntax is MATLAB2017a+ so it limits the scope of the tutorial (first paths block).
  * the `genpath(codedir)` in the first block is MATLAB2018a+
* [x] Write legacy example script: done in #10
* [ ] Update the actual toolbox code #11

**Comment by KirstieJane** [comment]
Thanks @TimVanMourik! I've let the other authors know about this issue and they'll swing by and give their feedback soon. It might not be immediate as they all have other projects to work on, but stay tuned 😄 

From my point of view, I don't think I agree that the repository is clearer with the namings you suggest in #8 because the word tutorial was a very conscious choice! The goal is to orient people who aren't used to visiting a GitHub page to find a tutorial as quickly as possible.

Happy to continue this conversation but I'll let the authors of the code and preprint share their thoughts first!

(I don't code in matlab so I don't have any opinions on that front!)

**Comment by TimVanMourik** [comment]
Let's keep discussions on individual topics separate, so see #8 for response 🙂

**Comment by pog87** [comment]
> Copies of the example data is present to both Python and Matlab directories.
I want the tutorial to work with python>=2.7, and the 2.x python doesn't support the commands of the form
```
pd.read_csv("../filename.csv")
```

**Comment by KirstieJane** [comment]
@pog87 - I think you can run that command with python 2.x......I just tried it in a local terminal and it worked fine.

Can you send the error you're getting in a python 2.7 environment?

**Comment by pog87** [comment]
@KirstieJane you are right! we can move the three csv files in a "data/" folder and let the three tutorials load "../data/file.csv" instead of "file.csv"

**Comment by TimVanMourik** [comment]
Awesome :) Is there a particular (dependency?) reason that the example file is Python 2 and not 3? Maybe an enhancement issue can be made for making a Python 3 version of the tutorial?

**Comment by KirstieJane** [comment]
@TimVanMourik - which file is written in python 2? I think the tutorial runs in 3 (these are the [environment setup commands](https://github.com/RainCloudPlots/RainCloudPlots/blob/master/tutorial_python/raincloud_tutorial_python.ipynb) I've been using)

**Comment by pog87** [comment]
My point was to made the tutorial less version-dependent as possible. At this point the tutorial should be running fine on python 2.7+ *and* 3.x
